context:
  name: slsa-verifier
  version: 2.7.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/slsa-framework/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 156190a6c96ef20747a88d28b69ee7fe60dc4d0fce3f9037da86778dcfdd2af8
    target_directory: src

build:
  script:
    - cd src/cli/slsa-verifier
    - go-licenses save . --save_path ../../../library_licenses
    - if: win
      then: go build -v -buildmode=pie -trimpath -modcacherw -o %LIBRARY_BIN%\slsa-verifier.exe -ldflags="-s"
      else: go build -v -buildmode=pie -trimpath -modcacherw -o $PREFIX/bin/slsa-verifier -ldflags="-s -w"
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script: slsa-verifier --help

about:
  homepage: https://github.com/slsa-framework/slsa-verifier
  summary: Verify provenance from SLSA compliant builders
  description: slsa-verifier is a tool for verifying SLSA provenance that was generated by CI/CD builders. slsa-verifier verifies the provenance by verifying the cryptographic signatures on provenance to make sure it was created by the expected builder. It then verifies that various values such as the builder id, source code repository, ref (branch or tag) matches the expected values.
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  repository: https://github.com/slsa-framework/slsa-verifier

extra:
  recipe-maintainers:
    - xhochy
